version: "3.4"

services:
  technologiestiftungnextstadtpulsapi:
    image: technologiestiftungnextstadtpulsapi
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 4000:4000
